{"name": "test_get", "status": "broken", "statusDetails": {"message": "AttributeError: 'list' object has no attribute 'size'", "trace": "def test_get():\n        print(request.get(\"62a1058f6f047803e8ae8430\").text)\n        try:\n            response = request.get()\n            size = response.json()\n>           print(size.size)\nE           AttributeError: 'list' object has no attribute 'size'\n\ntests/test_cases.py:58: AttributeError"}, "start": 1654720877982, "stop": 1654720878612, "uuid": "95f24dd4-f426-40cb-a3a2-9ff4a246ce6a", "historyId": "2b92b699695a9523974c6c24893482f5", "testCaseId": "7537be7ec288323126f37ef343b9dbe9", "fullName": "tests.test_cases#test_get", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cases"}, {"name": "host", "value": "KSargsyanL2M"}, {"name": "thread", "value": "55641-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases"}]}