{"name": "Get method check in case of a correct payload and unique ID", "status": "failed", "statusDetails": {"message": "AssertionError: FAILURE: Access to deleted element\nassert 404 == 405\ntests/test_cases.py:105 in test_del_200() -> check.equal(get_response_by_deleted_id.status_code, 405, \"Access to deleted element\")\n------------------------------------------------------------\nFailed Checks: 1", "trace": "FAILURE: Access to deleted element\nassert 404 == 405\ntests/test_cases.py:105 in test_del_200() -> check.equal(get_response_by_deleted_id.status_code, 405, \"Access to deleted element\")\n------------------------------------------------------------\nFailed Checks: 1"}, "start": 1654726604411, "stop": 1654726606183, "uuid": "1de41495-a82e-454b-903a-38567da20645", "historyId": "6a9b314f005e0b34640515b7cca1708a", "testCaseId": "3b1ad1e0935836842f24b33fc63db1f0", "fullName": "tests.test_cases#test_del_200", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cases"}, {"name": "host", "value": "KSargsyanL2M"}, {"name": "thread", "value": "57049-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases"}]}